name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
      - run: tar -xf zig-linux-x86_64-0.13.0.tar.xz
      - name: Add Zig to PATH
        run: echo "${{ github.workspace }}/zig-linux-x86_64-0.13.0" >> $GITHUB_PATH
      - run: zig version
      - run: zig build
      - run: ls -la ./zig-out/bin
      - run: ./zig-out/bin/mines
