name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Setting up the environment"
      - run: pwd
      - run: ls -la
      - run: uname
      - run: uname -i
