name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Setting up the environment"
      - run: pwd
      - run: ls -la
      - run: uname
      - run: uname -i
      - run: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
      - run: tar -xf zig-linux-x86_64-0.13.0.tar.xz
      - run: export PATH=$PATH:$(pwd)/zig-linux-x86_64-0.13.0
      - run: zig version
